ARM: imx: build cpuidle-imx6sx.o for imx6ul
The imx6ul soc code gained support for cpuidle, but that causes
a link failure if CONFIG_SOC_IMX6SX is disabled:

arch/arm/mach-imx/mach-imx6ul.o: In function `imx6ul_init_late':
mach-imx6ul.c:(.init.text+0xc): undefined reference to `imx6sx_cpuidle_init'

This adds the file containing the imx6sx_cpuidle_init function
to the kernel for 6ul-only configurations.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: 547e8f526959 ("ARM: imx: add cpuidle support for i.mx6ul")
Signed-off-by: Shawn Guo <shawnguo@kernel.org>